/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_msu_cme_rdp_primerdesign_utils_Primer3Wrapper */

#ifndef _Included_edu_msu_cme_rdp_primerdesign_utils_Primer3Wrapper
#define _Included_edu_msu_cme_rdp_primerdesign_utils_Primer3Wrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_msu_cme_rdp_primerdesign_utils_Primer3Wrapper
 * Method:    initThermoPath
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_msu_cme_rdp_primerdesign_utils_Primer3Wrapper_initThermoPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_msu_cme_rdp_primerdesign_utils_Primer3Wrapper
 * Method:    calcTm
 * Signature: (Ljava/lang/String;DDDDII)D
 */
JNIEXPORT jdouble JNICALL Java_edu_msu_cme_rdp_primerdesign_utils_Primer3Wrapper_calcTm
  (JNIEnv *, jobject, jstring, jdouble, jdouble, jdouble, jdouble, jint, jint);

/*
 * Class:     edu_msu_cme_rdp_primerdesign_utils_Primer3Wrapper
 * Method:    calcThermo
 * Signature: (Ljava/lang/String;Ljava/lang/String;IDDDDDIII)D
 */
JNIEXPORT jdouble JNICALL Java_edu_msu_cme_rdp_primerdesign_utils_Primer3Wrapper_calcThermo
  (JNIEnv *, jobject, jstring, jstring, jint, jdouble, jdouble, jdouble, jdouble, jdouble, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
